// Generated by CoffeeScript 1.10.0
(function() {
  var checkTime, itsDay, itsNight, lullabyEvents;

  itsDay = function() {
    $('.night').removeClass('night');
    return $('body').addClass('day');
  };

  itsNight = function() {
    $('.day').removeClass('day');
    return $('body').addClass('night');
  };

  checkTime = function() {
    var hour, now, time;
    now = moment();
    hour = now.hour();
    console.log('now', now.hour());
    return time = (function() {
      switch (false) {
        case !(hour < 5 || hour > 20):
          return itsNight();
        case !(hour > 5 && hour < 20):
          return itsDay();
        default:
          return console.log('TIME TRAP');
      }
    })();
  };

  lullabyEvents = function() {
    var lullaby;
    lullaby = document.getElementById("lullaby");
    return $(".music-trigger").on('click', function() {
      if (!lullaby.paused) {
        return lullaby.pause();
      } else {
        return lullaby.play();
      }
    });
  };

  $(document).ready(function() {
    var checkTimeInterval;
    checkTime();
    lullabyEvents();
    return checkTimeInterval = setInterval(checkTime, 60000);
  });

}).call(this);
